openapi: "3.0.3"
info:
  title: YouTube Video Summarizer API
  version: "1.2.0"
  description: |
    API for summarizing YouTube videos and analyzing transcripts for
    logical fallacies. Accepts a YouTube URL, retrieves the transcript,
    generates a summary using GPT-4o-mini, performs fallacy analysis,
    and returns both results with video metadata.

    v1.2.0: Added automatic fallacy analysis to the summarize response.
    The response now includes an optional `fallacy_analysis` field
    containing identified logical fallacies with severity ratings,
    explanations, and illustrative examples.

servers:
  - url: http://localhost:8000
    description: Local development server

paths:
  /api/summarize:
    post:
      operationId: summarizeVideo
      summary: Summarize a YouTube video and analyze for fallacies
      description: |
        Accepts a YouTube video URL and an optional summary length
        percentage. Retrieves the transcript, generates a summary
        guided by the length preference, performs logical fallacy
        analysis, and returns all results with video metadata.

        Fallacy analysis is performed automatically. If the analysis
        fails, the summary is still returned with `fallacy_analysis`
        set to null.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SummarizeRequest"
            examples:
              default_length:
                summary: Default summary length (25%)
                value:
                  url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
              custom_length:
                summary: Short summary (10%)
                value:
                  url: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
                  length_percent: 10
      responses:
        "200":
          description: Summary and fallacy analysis generated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SummarizeResponse"
              example:
                summary: "This video discusses the key principles of..."
                metadata:
                  video_id: "dQw4w9WgXcQ"
                  title: "Example Video Title"
                  channel_name: "Example Channel"
                  duration_seconds: 212
                  thumbnail_url: "https://i.ytimg.com/vi/dQw4w9WgXcQ/hqdefault.jpg"
                fallacy_analysis:
                  summary:
                    total_fallacies: 2
                    high_severity: 1
                    medium_severity: 1
                    low_severity: 0
                    primary_tactics:
                      - "Ad Hominem"
                      - "Straw Man"
                  fallacies:
                    - timestamp: null
                      quote: "You can't trust his opinion because he dropped out of college."
                      fallacy_name: "Ad Hominem"
                      category: "Relevance"
                      severity: "high"
                      explanation: "This attacks the person's educational background rather than addressing the substance of their argument. A person's formal education does not determine the validity of their reasoning."
                      clear_example:
                        scenario: "Dismissing a mechanic's diagnosis because they didn't attend a prestigious university."
                        why_wrong: "The mechanic's expertise comes from hands-on experience, not their degree. Judging their competence by education is irrelevant to the diagnosis."
                    - timestamp: null
                      quote: "Everyone knows that this is the only way to solve the problem."
                      fallacy_name: "Bandwagon Appeal"
                      category: "Emotional Appeal"
                      severity: "medium"
                      explanation: "This asserts something is true because 'everyone' believes it, which is an appeal to popularity rather than evidence. The popularity of a belief does not establish its truth."
                      clear_example:
                        scenario: "Claiming a diet pill works because millions of people buy it."
                        why_wrong: "Sales figures reflect marketing effectiveness, not medical efficacy."
        "400":
          description: Invalid request (bad URL, playlist URL, etc.)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Video not found or transcript unavailable
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "422":
          description: Validation error (invalid length_percent value)
          content:
            application/json:
              schema:
                type: object
                description: Standard FastAPI/Pydantic validation error response
        "502":
          description: External service failure (OpenAI — summarization)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /api/health:
    get:
      operationId: healthCheck
      summary: Health check endpoint
      description: Returns the service status.
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "ok"
                required:
                  - status

components:
  schemas:
    SummarizeRequest:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          description: YouTube video URL
          example: "https://www.youtube.com/watch?v=dQw4w9WgXcQ"
        length_percent:
          type: integer
          description: |
            Target summary length as a percentage of the transcript's
            word count. Must be between 10 and 50, in increments of 5.
            Defaults to 25 if not provided.
          minimum: 10
          maximum: 50
          default: 25
          enum: [10, 15, 20, 25, 30, 35, 40, 45, 50]
          example: 25

    SummarizeResponse:
      type: object
      required:
        - summary
      properties:
        summary:
          type: string
          description: Generated text summary of the video
        metadata:
          $ref: "#/components/schemas/VideoMetadata"
        fallacy_analysis:
          $ref: "#/components/schemas/FallacyAnalysisResult"
          nullable: true
          description: |
            Logical fallacy analysis of the transcript. Null if
            fallacy analysis failed or was unavailable.

    FallacyAnalysisResult:
      type: object
      required:
        - summary
        - fallacies
      properties:
        summary:
          $ref: "#/components/schemas/FallacySummary"
        fallacies:
          type: array
          items:
            $ref: "#/components/schemas/Fallacy"
          description: List of identified fallacies (may be empty)

    FallacySummary:
      type: object
      required:
        - total_fallacies
        - high_severity
        - medium_severity
        - low_severity
        - primary_tactics
      properties:
        total_fallacies:
          type: integer
          description: Total number of fallacies identified
          minimum: 0
        high_severity:
          type: integer
          description: Count of high-severity fallacies
          minimum: 0
        medium_severity:
          type: integer
          description: Count of medium-severity fallacies
          minimum: 0
        low_severity:
          type: integer
          description: Count of low-severity fallacies
          minimum: 0
        primary_tactics:
          type: array
          items:
            type: string
          description: Most common fallacy types used in the transcript

    Fallacy:
      type: object
      required:
        - quote
        - fallacy_name
        - category
        - severity
        - explanation
        - clear_example
      properties:
        timestamp:
          type: string
          nullable: true
          description: Timestamp in the transcript, null if unavailable
        quote:
          type: string
          description: Exact passage from transcript containing the fallacy
        fallacy_name:
          type: string
          description: Name of the logical fallacy
        category:
          type: string
          enum:
            - Relevance
            - Presumption
            - Ambiguity
            - Emotional Appeal
            - Statistical
            - Manipulation
          description: Fallacy category
        severity:
          type: string
          enum:
            - high
            - medium
            - low
          description: Severity rating
        explanation:
          type: string
          description: 2-3 sentence explanation of why this qualifies as a fallacy
        clear_example:
          $ref: "#/components/schemas/ClearExample"

    ClearExample:
      type: object
      required:
        - scenario
        - why_wrong
      properties:
        scenario:
          type: string
          description: A simpler example of the same fallacy pattern in a different context
        why_wrong:
          type: string
          description: Brief explanation of why it is wrong

    VideoMetadata:
      type: object
      properties:
        video_id:
          type: string
          description: YouTube video ID (11 characters)
          example: "dQw4w9WgXcQ"
        title:
          type: string
          description: Video title
          nullable: true
        channel_name:
          type: string
          description: Channel or author name
          nullable: true
        duration_seconds:
          type: integer
          description: Approximate video duration in seconds
          nullable: true
        thumbnail_url:
          type: string
          description: Video thumbnail URL
          nullable: true

    ErrorResponse:
      type: object
      required:
        - error
        - message
      properties:
        error:
          type: string
          description: Machine-readable error code
          enum:
            - invalid_url
            - video_not_found
            - transcript_unavailable
            - playlist_not_supported
            - summarization_failed
            - internal_error
        message:
          type: string
          description: Human-readable, actionable error message
        details:
          type: string
          description: Additional context or suggestions
          nullable: true
